import "./globals.css"

import cx from "classnames"
import type { Metadata } from "next"
import { Inter } from "next/font/google"

import { HeaderNavigation } from "./ui/HeaderNavigation"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={cx("bg-background-color text-font-color", inter.className)}
      >
        <HeaderNavigation />
        {children}
      </body>
    </html>
  )
}
